#pragma once

/// \file
/// The tensor-product grid: the first concrete grid under `pantr/grid/grid.hpp`.
///
/// A tensor product of axis-aligned boxes, stored as one strictly increasing
/// breakpoint vector per axis. Cells are numbered row-major (C order) over the
/// per-axis cell counts, so a grid and a `SpanwiseElementExtraction` built on the same
/// B-spline space agree on cell ids.
///
/// ## What it specialises, and what it deliberately does not
///
/// Three of the mixin's fourteen replaceable defaults, which is exactly what the
/// Python oracle `src/pantr/grid/_tensor_product_grid.py` replaces: `locate_many`,
/// `collect_cell_bounds` and `restrict`. `grid_traits` declares those three and
/// `PANTR_GRID_CENSUS` rejects a fourth written by accident or a declared one never
/// written. The census runs at BOTH `float` and `double`, which forces every default
/// body at a scalar no binding registers; `design/backend_parity.md` Rule 8 is why
/// only `double` is bound, and the `float` instantiation opens no parity claim.
///
/// `locate` and `cell_bounds` are primitives rather than hooks, so they do not appear
/// in the bitmask. `boundary_facets`, `neighbors` and the rest run generically: a
/// tensor-product grid has structure that would let them be specialised, and doing so
/// is a separate decision with its own differential test to write.
///
/// ## The flat layout is built once, at construction
///
/// The breakpoints live in ONE contiguous `breakpoints_flat_` with a per-axis start
/// offset, rather than as a vector of vectors. That is the layout the per-axis binary
/// search wants, and holding it as state is the point of the type: the Python oracle
/// rebuilt it -- a concatenate plus three arrays -- on every `locate_many` call, and
/// nothing about it depends on the query. `breakpoints(axis)` hands out a view into
/// it, so the address of `breakpoints(0).data()` is stable for the grid's lifetime and
/// a test can say so.
///
/// ## The differential oracle
///
/// `Base` is a PUBLIC alias, deliberately. A specialisation owes its default a
/// comparison, and the way to reach a hidden default is the qualified call
/// `g.pantr::grid::GridBase<G>::collect_cell_bounds(...)`; a private alias would make
/// the name unreachable from the test. See `cpp/tests/test_grid_defaults.cpp`.
///
/// ## `uniform_grid` reproduces numpy's `linspace` bit for bit
///
/// The factory is not "start plus i times step": it is numpy's own sequence, because
/// the Python oracle calls `numpy.linspace` and a grid built under one backend must
/// carry the same coordinates as one built under the other. Three details are
/// load-bearing and each is a bug if dropped -- the `step == 0` branch, the exact
/// assignment of the final breakpoint to `stop`, and the SEPARATE statements for the
/// product and the sum. See `uniform_grid` for the derivation of each.

#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <span>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include "pantr/core/mdspan.hpp"
#include "pantr/core/scalar.hpp"
#include "pantr/grid/grid.hpp"

namespace pantr::grid {

template <class T>
class TensorProductGrid;

/// The smallest useful breakpoint vector: two entries, hence one cell.
inline constexpr std::int64_t kMinBreakpointsPerAxis = 2;

/// The multiple of `eps` `is_uniform` allows the per-axis spacings to differ by.
///
/// **This is a relative tolerance applied to the COORDINATE SCALE**, not an absolute
/// one, and that is a correction rather than a transliteration. The oracle used a bare
/// `1e-10` justified by cell count, which is wrong in both halves: the spread does not
/// grow with the cell count, and it does grow with the coordinate magnitude. Measured,
/// `uniform_grid([[1e6, 1e6 + 1]], 100)` -- an exact `linspace` grid -- reported
/// `is_uniform == False` under the absolute constant.
///
/// ## The derivation
///
/// Let an axis run from `a` to `b` over `n` cells, generated by `linspace`, and write
/// `u = eps / 2` for the unit roundoff and `S = |a| + |b|`, which dominates both the
/// largest coordinate `max(|a|, |b|)` and the extent `b - a`. The generated breakpoint
/// is `x_i = fl(fl(i * fl(fl(b - a) / n)) + a)`, four roundings:
///
///   - `delta = (b - a)(1 + e1)`, `|e1| <= u`;
///   - `step = (delta / n)(1 + e2)`;
///   - `p_i = (i * step)(1 + e3)`, and `|i * (b - a) / n| <= |b - a| <= S`;
///   - `x_i = (p_i + a)(1 + e4)`, and `|p_i + a| <= max(|a|, |b|) <= S`.
///
/// To first order `|x_i - (a + i (b - a) / n)| <= 4 u S`. The stored spacing is
/// `d_i = fl(x_{i+1} - x_i)`, which adds one rounding of a quantity no larger than
/// `S`, so `|d_i - (b - a) / n| <= 9 u S`, and the spread of the spacings is at most
/// twice that: `ptp(d) <= 18 u S = 9 eps S`. **The bound has no `n` in it**, which is
/// the half the oracle's rationale got backwards.
///
/// Rounded up to the next power of two, `16 eps` -- a stated margin of 1.8 over the
/// derivation. Measured over 200000 random `linspace` axes spanning forty decades of
/// magnitude, the largest observed `ptp(d) / (eps S)` was 2.74, so the constant also
/// carries a factor of 5.8 over anything seen.
///
/// ## Where it degrades, and how
///
/// `16 eps S` underflows to zero for `S` below about `1e-292`, where the test becomes
/// exact equality of the spacings. That is the honest answer at that scale rather than
/// a failure: every coordinate there is subnormal, and a tolerance smaller than the
/// smallest subnormal cannot be represented to compare against.
///
/// The Python oracle carries the same constant and the same derivation at
/// `src/pantr/grid/_tensor_product_grid.py`; the two are compared in
/// `tests/parity/test_grid_types.py`.
inline constexpr int kUniformSpacingEpsFactor = 16;

}  // namespace pantr::grid

/// The tensor-product grid's traits: `double` or `float`, and its three hooks.
///
/// \tparam T The scalar type.
template <class T>
struct pantr::grid::grid_traits<pantr::grid::TensorProductGrid<T>> {
    /// The floating-point type the grid's coordinates are stored in.
    using scalar_type = T;

    /// The three defaults this grid replaces; see the file header.
    static constexpr pantr::grid::Hook hooks =
        pantr::grid::Hook::locate_many | pantr::grid::Hook::collect_cell_bounds
        | pantr::grid::Hook::restrict;
};

namespace pantr::grid {

/// A tensor product of axis-aligned boxes with per-axis breakpoint vectors.
///
/// Cells are numbered row-major over `cells_per_axis()`, last axis varying fastest.
/// Immutable after construction apart from the base's lazily built BVH.
///
/// \tparam T The scalar type; `double` is the only one bound to Python.
template <class T>
class TensorProductGrid : public GridBase<TensorProductGrid<T>> {
  public:
    /// The generic mixin, named publicly so a differential test can reach the defaults
    /// this grid hides. See the file header.
    using Base = GridBase<TensorProductGrid<T>>;

    /// Build a grid from one strictly increasing breakpoint vector per axis.
    ///
    /// \param breakpoints One vector per axis, each with at least two finite,
    ///        strictly increasing entries.
    /// \throws std::invalid_argument If there are no axes, or an axis is too short,
    ///         non-finite, or not strictly increasing.
    explicit TensorProductGrid(const std::vector<std::vector<T>>& breakpoints)
        : TensorProductGrid(breakpoints, checked_sizes(breakpoints)) {}

    // ----------------------------------------------------------------
    // Read-only geometry
    // ----------------------------------------------------------------

    /// The per-axis cell counts.
    ///
    /// \return A view of length `ndim`, valid for the grid's lifetime.
    [[nodiscard]] std::span<const std::int64_t> cells_per_axis() const noexcept {
        return cells_per_axis_;
    }

    /// The per-axis C-order flat strides.
    ///
    /// \return A view of length `ndim`, valid for the grid's lifetime.
    [[nodiscard]] std::span<const std::int64_t> strides() const noexcept { return strides_; }

    /// One axis's breakpoint vector.
    ///
    /// A view into the grid's single flat buffer rather than a copy, so its address is
    /// stable for the grid's lifetime; that is what lets a test assert the layout was
    /// packed once.
    ///
    /// \param axis Axis index in `[0, ndim)`.
    /// \return A view of length `cells_per_axis()[axis] + 1`.
    /// \throws std::out_of_range If `axis` is out of range.
    [[nodiscard]] std::span<const T> breakpoints(std::int64_t axis) const {
        check_axis(axis);
        const auto d = static_cast<std::size_t>(axis);
        const auto start = static_cast<std::size_t>(axis_start_[d]);
        const auto count = static_cast<std::size_t>(cells_per_axis_[d] + 1);
        return std::span<const T>(breakpoints_flat_.data() + start, count);
    }

    /// Whether every axis's breakpoint spacing is constant.
    ///
    /// Constant to within `kUniformSpacingEpsFactor * eps * (|first| + |last|)`; see
    /// that constant for the derivation and for why the tolerance is relative.
    ///
    /// \return `true` iff every axis is uniformly spaced within that tolerance.
    [[nodiscard]] bool is_uniform() const noexcept { return is_uniform_; }

    // ----------------------------------------------------------------
    // Index helpers (row-major C order)
    // ----------------------------------------------------------------

    /// The per-axis indices of cell `cid`.
    ///
    /// \param cid Flat cell identifier.
    /// \param out Output per-axis indices, length `ndim`.
    /// \throws std::out_of_range If `cid` is out of range.
    /// \throws std::invalid_argument If `out` is not length `ndim`.
    void cell_multi_index(std::int64_t cid, std::span<std::int64_t> out) const {
        check_flat_cid(cid);
        require_ndim_span(out, "out");
        decompose(cid, out);
    }

    /// The flat cell identifier of a per-axis index tuple.
    ///
    /// \param multi Per-axis indices, length `ndim`.
    /// \return The flat cell identifier.
    /// \throws std::invalid_argument If `multi` is not length `ndim`.
    /// \throws std::out_of_range If any index is outside its axis's cell range.
    [[nodiscard]] std::int64_t flat_cell_index(std::span<const std::int64_t> multi) const {
        const auto ndim = static_cast<std::size_t>(this->ndim());
        if (multi.size() != ndim) {
            throw std::invalid_argument("multi-index has length " + std::to_string(multi.size())
                                        + "; expected " + std::to_string(ndim) + ".");
        }
        std::int64_t cid = 0;
        for (std::size_t d = 0; d < multi.size(); ++d) {
            if (multi[d] < 0 || multi[d] >= cells_per_axis_[d]) {
                throw std::out_of_range("axis " + std::to_string(d) + " index "
                                        + std::to_string(multi[d]) + " out of range [0, "
                                        + std::to_string(cells_per_axis_[d]) + ").");
            }
            cid += multi[d] * strides_[d];
        }
        return cid;
    }

    // ----------------------------------------------------------------
    // The three primitives
    // ----------------------------------------------------------------

    /// Cell `cid`'s axis-aligned corners.
    ///
    /// \param cid Cell identifier.
    /// \param lo Output lo corner, length `ndim`.
    /// \param hi Output hi corner, length `ndim`.
    /// \throws std::out_of_range If `cid` is out of range.
    /// \throws std::invalid_argument If either span is not length `ndim`.
    void cell_bounds(std::int64_t cid, std::span<T> lo, std::span<T> hi) const {
        check_flat_cid(cid);
        require_ndim_span(lo, "lo");
        require_ndim_span(hi, "hi");
        for (std::size_t d = 0; d < lo.size(); ++d) {
            const std::int64_t i = (cid / strides_[d]) % cells_per_axis_[d];
            const T* bp = breakpoints_flat_.data() + axis_start_[d];
            lo[d] = bp[i];
            hi[d] = bp[i + 1];
        }
    }

    /// The cell containing `pt`, or nothing if `pt` lies outside the grid.
    ///
    /// A point on an interior breakpoint goes to the lower-indexed cell sharing that
    /// face; a point on the outer boundary goes to the adjacent boundary cell. A
    /// non-finite coordinate is outside every cell.
    ///
    /// \param pt Query point, length `ndim`.
    /// \return The containing cell id, or `std::nullopt`.
    /// \throws std::invalid_argument If `pt` is not length `ndim`.
    [[nodiscard]] std::optional<std::int64_t> locate(std::span<const T> pt) const {
        require_ndim_span(pt, "pt");
        std::int64_t cid = 0;
        for (std::size_t d = 0; d < pt.size(); ++d) {
            const std::int64_t i = axis_cell(d, pt[d]);
            if (i < 0) {
                return std::nullopt;
            }
            cid += i * strides_[d];
        }
        return cid;
    }

    /// The cell across local facet `lfid` of `cid`, or nothing on a boundary facet.
    ///
    /// Uses the `lfid = 2 * axis + side` encoding, with `side == 0` the low face.
    ///
    /// \param cid Cell identifier.
    /// \param lfid Local facet identifier in `[0, 2 * ndim)`.
    /// \return The neighbouring cell id, or `std::nullopt`.
    /// \throws std::out_of_range If `cid` or `lfid` is out of range.
    [[nodiscard]] std::optional<std::int64_t> neighbor_across_facet(std::int64_t cid,
                                                                    std::int64_t lfid) const {
        this->check_lfid(cid, lfid);
        const auto axis = static_cast<std::size_t>(lfid / 2);
        const std::int64_t side = lfid % 2;
        const std::int64_t i = (cid / strides_[axis]) % cells_per_axis_[axis];
        if (side == 0) {
            if (i == 0) {
                return std::nullopt;
            }
            return cid - strides_[axis];
        }
        if (i == cells_per_axis_[axis] - 1) {
            return std::nullopt;
        }
        return cid + strides_[axis];
    }

    // ----------------------------------------------------------------
    // The three hooks
    // ----------------------------------------------------------------

    /// Locate a batch of points, one cell id per point.
    ///
    /// Replaces the generic default, which calls `locate` per point through
    /// `std::optional` and a freshly formed span. This one hoists the per-axis
    /// pointers out of the loop and writes the sentinel directly. The verdict is the
    /// same by construction: both reach `axis_cell`, which is where the location rule
    /// is defined once. What the differential test in `cpp/tests/test_grid_defaults.cpp`
    /// checks is the composition around it -- the strides, the output order and the
    /// `-1` convention -- which is where an error would actually be.
    ///
    /// \param points `(npts, ndim)` row-major view of query points.
    /// \return `npts` cell ids; `-1` for a point outside every cell.
    /// \throws std::invalid_argument If `points.extent(1)` is not `ndim`.
    [[nodiscard]] std::vector<std::int64_t> locate_many(span2d<const T> points) const {
        const auto ndim = static_cast<std::size_t>(this->ndim());
        if (points.extent(1) != ndim) {
            throw std::invalid_argument("points must have " + std::to_string(ndim)
                                        + " columns (ndim); got "
                                        + std::to_string(points.extent(1)) + ".");
        }
        const std::size_t npts = points.extent(0);
        std::vector<std::int64_t> out(npts);
        for (std::size_t p = 0; p < npts; ++p) {
            std::int64_t cid = 0;
            for (std::size_t d = 0; d < ndim; ++d) {
                const std::int64_t i = axis_cell(d, at(points, p, d));
                if (i < 0) {
                    cid = -1;
                    break;
                }
                cid += i * strides_[d];
            }
            out[p] = cid;
        }
        return out;
    }

    /// Materialise per-cell `(lo, hi)` into `(num_cells, ndim)` views.
    ///
    /// Replaces the generic default, which decomposes every cell id into its per-axis
    /// indices. Here each axis's index pattern is written directly: along axis `d` the
    /// index is held for `strides()[d]` consecutive rows and the whole pattern repeats
    /// with period `strides()[d] * cells_per_axis()[d]`, so no division is needed.
    /// Every value written is a COPY of a stored breakpoint -- no arithmetic is
    /// performed -- which is why the differential comparison against the default is an
    /// exact equality rather than a bounded one.
    ///
    /// \param cell_lo Output lo corners, shape `(num_cells, ndim)`.
    /// \param cell_hi Output hi corners, same shape.
    /// \throws std::invalid_argument If either view is not shaped `(num_cells, ndim)`.
    void collect_cell_bounds(span2d<T> cell_lo, span2d<T> cell_hi) const {
        const auto rows = static_cast<std::size_t>(this->num_cells());
        const auto ndim = static_cast<std::size_t>(this->ndim());
        require_shape(cell_lo, rows, ndim, "cell_lo");
        require_shape(cell_hi, rows, ndim, "cell_hi");
        for (std::size_t d = 0; d < ndim; ++d) {
            const T* bp = breakpoints_flat_.data() + axis_start_[d];
            const auto stride = static_cast<std::size_t>(strides_[d]);
            const auto count = static_cast<std::size_t>(cells_per_axis_[d]);
            std::size_t row = 0;
            while (row < rows) {
                for (std::size_t i = 0; i < count; ++i) {
                    for (std::size_t k = 0; k < stride; ++k, ++row) {
                        at(cell_lo, row, d) = bp[i];
                        at(cell_hi, row, d) = bp[i + 1];
                    }
                }
            }
        }
    }

    /// The multi-index bounding-box sub-grid spanning `cell_ids`.
    ///
    /// The window is the axis-aligned bounding box of the requested cells in
    /// multi-index space. Each axis of the sub-grid is a pure SLICE of this grid's
    /// breakpoints, never re-based or re-clamped, so the sub-grid's cells coincide
    /// exactly with the matching cells of this grid.
    ///
    /// Replaces the generic default, which throws: restriction is an optional grid
    /// capability and a tensor-product grid has it.
    ///
    /// \param cell_ids Flat cell identifiers to span; duplicates are ignored.
    /// \return The windowed sub-grid, its `local_to_global_cell` map, and the
    ///         `in_subset` mask flagging requested against bounding-box-fill cells.
    /// \throws std::invalid_argument If `cell_ids` is empty.
    /// \throws std::out_of_range If any cell id is outside `[0, num_cells)`.
    [[nodiscard]] GridRestriction<TensorProductGrid<T>> restrict(
        std::span<const std::int64_t> cell_ids) const {
        if (cell_ids.empty()) {
            throw std::invalid_argument("restrict: cell_ids must be non-empty.");
        }
        const auto ndim = static_cast<std::size_t>(this->ndim());
        std::int64_t lo_id = cell_ids[0];
        std::int64_t hi_id = cell_ids[0];
        for (const std::int64_t cid : cell_ids) {
            lo_id = cid < lo_id ? cid : lo_id;
            hi_id = cid > hi_id ? cid : hi_id;
        }
        if (lo_id < 0 || hi_id >= this->num_cells()) {
            throw std::out_of_range("restrict: cell id out of range [0, "
                                    + std::to_string(this->num_cells()) + "); got ["
                                    + std::to_string(lo_id) + ", " + std::to_string(hi_id)
                                    + "].");
        }

        std::vector<std::int64_t> imin(ndim);
        std::vector<std::int64_t> imax(ndim);
        std::vector<std::int64_t> multi(ndim);
        decompose(cell_ids[0], multi);
        imin = multi;
        imax = multi;
        for (const std::int64_t cid : cell_ids) {
            decompose(cid, multi);
            for (std::size_t d = 0; d < ndim; ++d) {
                imin[d] = multi[d] < imin[d] ? multi[d] : imin[d];
                imax[d] = multi[d] > imax[d] ? multi[d] : imax[d];
            }
        }

        std::vector<std::vector<T>> sub_breakpoints(ndim);
        for (std::size_t d = 0; d < ndim; ++d) {
            const std::span<const T> bp = breakpoints(static_cast<std::int64_t>(d));
            const T* first = bp.data() + imin[d];
            const T* last = bp.data() + imax[d] + 2;
            sub_breakpoints[d].assign(first, last);
        }
        TensorProductGrid<T> sub(sub_breakpoints);

        const auto sub_cells = static_cast<std::size_t>(sub.num_cells());
        std::vector<std::int64_t> local_to_global(sub_cells);
        std::vector<std::int64_t> sub_multi(ndim);
        for (std::size_t local = 0; local < sub_cells; ++local) {
            sub.decompose(static_cast<std::int64_t>(local), sub_multi);
            std::int64_t global = 0;
            for (std::size_t d = 0; d < ndim; ++d) {
                global += (sub_multi[d] + imin[d]) * strides_[d];
            }
            local_to_global[local] = global;
        }

        // `in_subset` is membership in the REQUESTED set, which may be a strict subset
        // of the window when the request is non-convex. Sorting a copy of the request
        // makes the test logarithmic rather than making it quadratic in the window.
        std::vector<std::int64_t> requested(cell_ids.begin(), cell_ids.end());
        sort_ids(requested);
        std::vector<std::uint8_t> in_subset(sub_cells);
        for (std::size_t local = 0; local < sub_cells; ++local) {
            in_subset[local] = contains_sorted(requested, local_to_global[local]) ? 1 : 0;
        }
        return make_restriction(std::move(sub), std::move(local_to_global), std::move(in_subset));
    }

    /// A compact representation, matching the Python wrapper's `__repr__` exactly.
    ///
    /// Character-for-character, trailing comma of a one-tuple included, so that a C++
    /// consumer and a Python one print the same grid the same way.
    ///
    /// \return `"TensorProductGrid(ndim=..., cells_per_axis=(...), uniform=...)"`.
    [[nodiscard]] std::string to_string() const {
        std::string text = "TensorProductGrid(ndim=" + std::to_string(this->ndim())
                           + ", cells_per_axis=(";
        for (std::size_t d = 0; d < cells_per_axis_.size(); ++d) {
            if (d > 0) {
                text += ", ";
            }
            text += std::to_string(cells_per_axis_[d]);
        }
        if (cells_per_axis_.size() == 1) {
            text += ",";
        }
        text += "), uniform=";
        text += is_uniform_ ? "True" : "False";
        text += ")";
        return text;
    }

  private:
    /// The two sizes the mixin's constructor needs, computed once from validated input.
    struct Sizes {
        std::int64_t ndim;       ///< Number of axes.
        std::int64_t num_cells;  ///< Product of the per-axis cell counts.
    };

    /// Establish the flat layout, the strides and the uniformity flag.
    ///
    /// Delegated to rather than done in the public constructor because the order in
    /// which a constructor's ARGUMENTS are evaluated is unspecified: computing the two
    /// sizes as two separate calls could run the cell-count product before the
    /// validation, on input that has not been checked.
    ///
    /// \param breakpoints The already-validated per-axis vectors.
    /// \param sizes The dimension and cell count `checked_sizes` derived from them.
    TensorProductGrid(const std::vector<std::vector<T>>& breakpoints, Sizes sizes)
        : Base(sizes.ndim, sizes.num_cells),
          cells_per_axis_(static_cast<std::size_t>(sizes.ndim)),
          axis_start_(static_cast<std::size_t>(sizes.ndim)),
          strides_(static_cast<std::size_t>(sizes.ndim)) {
        std::size_t total = 0;
        for (std::size_t d = 0; d < breakpoints.size(); ++d) {
            axis_start_[d] = static_cast<std::int64_t>(total);
            cells_per_axis_[d] = static_cast<std::int64_t>(breakpoints[d].size()) - 1;
            total += breakpoints[d].size();
        }
        breakpoints_flat_.reserve(total);
        for (const std::vector<T>& axis : breakpoints) {
            breakpoints_flat_.insert(breakpoints_flat_.end(), axis.begin(), axis.end());
        }
        std::int64_t stride = 1;
        for (std::size_t d = cells_per_axis_.size(); d-- > 0;) {
            strides_[d] = stride;
            stride *= cells_per_axis_[d];
        }
        is_uniform_ = true;
        for (std::size_t d = 0; d < cells_per_axis_.size() && is_uniform_; ++d) {
            is_uniform_ = axis_is_uniform(breakpoints[d]);
        }
    }

    /// Validate the breakpoints and return the sizes they imply.
    ///
    /// \param breakpoints The candidate per-axis vectors.
    /// \return The dimension and the cell count.
    /// \throws std::invalid_argument If there are no axes, or an axis is too short,
    ///         non-finite, or not strictly increasing.
    [[nodiscard]] static Sizes checked_sizes(const std::vector<std::vector<T>>& breakpoints) {
        using pantr::value_of;
        if (breakpoints.empty()) {
            throw std::invalid_argument(
                "TensorProductGrid needs at least one axis; got 0.");
        }
        std::int64_t num_cells = 1;
        for (std::size_t d = 0; d < breakpoints.size(); ++d) {
            const std::vector<T>& axis = breakpoints[d];
            if (static_cast<std::int64_t>(axis.size()) < kMinBreakpointsPerAxis) {
                throw std::invalid_argument(
                    "breakpoints[" + std::to_string(d) + "] must have at least "
                    + std::to_string(kMinBreakpointsPerAxis) + " entries (>= 1 cell); got "
                    + std::to_string(axis.size()) + ".");
            }
            for (const T& x : axis) {
                const auto v = value_of(x);
                // Written as a negated pair rather than as `isfinite`: the comparison
                // is false for a NaN and for either infinity, which is exactly the
                // rejection, and it goes through `value_of` as the scalar-generic
                // disciplines require.
                if (!(v > -std::numeric_limits<decltype(v)>::infinity()
                      && v < std::numeric_limits<decltype(v)>::infinity())) {
                    throw std::invalid_argument("breakpoints[" + std::to_string(d)
                                                + "] must contain only finite values.");
                }
            }
            for (std::size_t i = 0; i + 1 < axis.size(); ++i) {
                if (!(value_of(axis[i]) < value_of(axis[i + 1]))) {
                    throw std::invalid_argument("breakpoints[" + std::to_string(d)
                                                + "] must be strictly increasing.");
                }
            }
            num_cells *= static_cast<std::int64_t>(axis.size()) - 1;
        }
        return Sizes{static_cast<std::int64_t>(breakpoints.size()), num_cells};
    }

    /// Whether one axis's spacings are constant to the derived tolerance.
    ///
    /// \param axis The axis's breakpoints, already validated.
    /// \return `true` iff `ptp(diff(axis))` is within the tolerance; an axis of one
    ///         cell has no two spacings to compare and is uniform by definition.
    [[nodiscard]] static bool axis_is_uniform(const std::vector<T>& axis) {
        using pantr::value_of;
        if (axis.size() <= static_cast<std::size_t>(kMinBreakpointsPerAxis)) {
            return true;
        }
        auto smallest = value_of(axis[1]) - value_of(axis[0]);
        auto largest = smallest;
        for (std::size_t i = 1; i + 1 < axis.size(); ++i) {
            const auto d = value_of(axis[i + 1]) - value_of(axis[i]);
            smallest = d < smallest ? d : smallest;
            largest = d > largest ? d : largest;
        }
        using V = decltype(smallest);
        const V first = value_of(axis.front());
        const V last = value_of(axis.back());
        const V scale = (first < V{0} ? -first : first) + (last < V{0} ? -last : last);
        return largest - smallest
               <= static_cast<V>(kUniformSpacingEpsFactor) * std::numeric_limits<V>::epsilon()
                      * scale;
    }

    /// The per-axis index of `x` along axis `d`, or `-1` if it lies outside.
    ///
    /// The one place the location rule is written: a half-open search that puts a
    /// point on an interior breakpoint in the lower cell and a point on either outer
    /// boundary in the adjacent one. The membership test is a NEGATED chained
    /// comparison, which rejects a NaN as well as either infinity -- the oracle's
    /// batch kernel instead tests `x < first || x > last`, which a NaN passes, and
    /// masks the non-finite rows afterwards; the two agree on every input, and this
    /// form needs no second pass.
    ///
    /// \param d Axis index.
    /// \param x The coordinate.
    /// \return The cell index in `[0, cells_per_axis()[d])`, or `-1`.
    [[nodiscard]] std::int64_t axis_cell(std::size_t d, const T& x) const {
        using pantr::value_of;
        const T* bp = breakpoints_flat_.data() + axis_start_[d];
        const std::int64_t count = cells_per_axis_[d];
        const auto v = value_of(x);
        if (!(value_of(bp[0]) <= v && v <= value_of(bp[count]))) {
            return -1;
        }
        // The first index with `bp[i] >= x`, which is numpy's `searchsorted(side="left")`.
        std::int64_t lo = 0;
        std::int64_t hi = count + 1;
        while (lo < hi) {
            const std::int64_t mid = lo + ((hi - lo) / 2);
            if (value_of(bp[mid]) < v) {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        const std::int64_t cell = lo - 1;
        if (cell < 0) {
            return 0;
        }
        return cell > count - 1 ? count - 1 : cell;
    }

    /// Write `cid`'s per-axis indices into `out`, unchecked.
    ///
    /// \param cid A cell identifier already known to be in range.
    /// \param out Output per-axis indices, already known to be length `ndim`.
    void decompose(std::int64_t cid, std::span<std::int64_t> out) const noexcept {
        for (std::size_t d = 0; d < out.size(); ++d) {
            out[d] = (cid / strides_[d]) % cells_per_axis_[d];
        }
    }

    /// Sort a scratch copy of the requested cell ids in place.
    ///
    /// An insertion-free ascending sort written out rather than `std::sort`, so the
    /// header needs no `<algorithm>`; the array is the caller's request, which is at
    /// most `num_cells` long.
    ///
    /// \param ids The ids to sort.
    static void sort_ids(std::vector<std::int64_t>& ids) noexcept {
        for (std::size_t i = 1; i < ids.size(); ++i) {
            const std::int64_t key = ids[i];
            std::size_t j = i;
            while (j > 0 && ids[j - 1] > key) {
                ids[j] = ids[j - 1];
                --j;
            }
            ids[j] = key;
        }
    }

    /// Whether a sorted array contains `value`.
    ///
    /// \param sorted An ascending array.
    /// \param value The value to look for.
    /// \return `true` iff it is present.
    [[nodiscard]] static bool contains_sorted(const std::vector<std::int64_t>& sorted,
                                              std::int64_t value) noexcept {
        std::size_t lo = 0;
        std::size_t hi = sorted.size();
        while (lo < hi) {
            const std::size_t mid = lo + ((hi - lo) / 2);
            if (sorted[mid] < value) {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }
        return lo < sorted.size() && sorted[lo] == value;
    }

    /// Reject a cell id outside `[0, num_cells)`, in the index helpers' own words.
    ///
    /// **A second spelling of the mixin's `check_cid`, and it is a transliteration
    /// rather than a choice.** The Python oracle reaches this condition by two routes
    /// that word it differently: `cell_level` goes through `Grid._check_cid` and says
    /// *"cell id N is out of range"*, while `cell_bounds` goes through
    /// `cell_multi_index` into `pantr.grid._cell_index.flat_to_multi` and says *"flat
    /// cell id N is out of range"*. Both are shipped public messages, so the port
    /// reproduces both; a single wording here would change one of them for a reason
    /// internal to the C++ layer. The inconsistency is the oracle's and is worth
    /// removing on the Python side one day, in a change that owns it.
    ///
    /// \param cid Candidate cell identifier.
    /// \throws std::out_of_range If `cid` is negative or `>= num_cells`.
    void check_flat_cid(std::int64_t cid) const {
        if (cid < 0 || cid >= this->num_cells()) {
            throw std::out_of_range("flat cell id " + std::to_string(cid)
                                    + " is out of range [0, "
                                    + std::to_string(this->num_cells()) + ").");
        }
    }

    /// Reject an axis index outside `[0, ndim)`.
    ///
    /// \param axis The candidate axis.
    /// \throws std::out_of_range If it is out of range.
    void check_axis(std::int64_t axis) const {
        if (axis < 0 || axis >= this->ndim()) {
            throw std::out_of_range("axis " + std::to_string(axis) + " is out of range [0, "
                                    + std::to_string(this->ndim()) + ").");
        }
    }

    /// Reject a span whose length is not `ndim`.
    ///
    /// Unconditional rather than `PANTR_PRECONDITION`, for the reason the mixin's own
    /// span checks give: that macro is `assert` and vanishes under `NDEBUG`, and a
    /// caller-supplied span is exactly the case the sibling types check always.
    ///
    /// \tparam U The span's element type.
    /// \param s The candidate span.
    /// \param what The parameter's name, for the message.
    /// \throws std::invalid_argument If its length is not `ndim`.
    template <class U>
    void require_ndim_span(std::span<U> s, const char* what) const {
        const auto n = static_cast<std::size_t>(this->ndim());
        if (s.size() != n) {
            throw std::invalid_argument(std::string(what) + " must have length ndim ("
                                        + std::to_string(n) + "); got "
                                        + std::to_string(s.size()) + ".");
        }
    }

    /// Reject a two-dimensional view that is not shaped `(rows, cols)`.
    ///
    /// \param view The candidate view.
    /// \param rows The row count it must have.
    /// \param cols The column count it must have.
    /// \param what The parameter's name, for the message.
    /// \throws std::invalid_argument If either extent is wrong.
    static void require_shape(span2d<T> view, std::size_t rows, std::size_t cols,
                              const char* what) {
        if (view.extent(0) != rows || view.extent(1) != cols) {
            throw std::invalid_argument(
                std::string(what) + " must have shape (" + std::to_string(rows) + ", "
                + std::to_string(cols) + "); got (" + std::to_string(view.extent(0)) + ", "
                + std::to_string(view.extent(1)) + ").");
        }
    }

    std::vector<T> breakpoints_flat_;           ///< Every axis's breakpoints, end to end.
    std::vector<std::int64_t> cells_per_axis_;  ///< Per-axis cell counts.
    std::vector<std::int64_t> axis_start_;      ///< Per-axis offset into the flat buffer.
    std::vector<std::int64_t> strides_;         ///< Per-axis C-order flat strides.
    bool is_uniform_ = false;                   ///< Whether every axis is uniformly spaced.
};

/// Build a uniform grid on a bounding box.
///
/// The breakpoints are numpy's `linspace` sequence, reproduced rather than
/// approximated. Three details carry that claim, and each is a defect if dropped:
///
///  - **The `step == 0` branch.** numpy divides the index by the cell count first and
///    multiplies by the extent second when `extent / cells` underflows to zero, which
///    is the only thing that keeps a grid on a subnormal extent from collapsing to a
///    constant.
///  - **The final breakpoint is ASSIGNED `stop`.** numpy overwrites it rather than
///    computing it, so the grid's upper bound is exact and `locate` at the boundary
///    cannot fall outside by a bit.
///  - **The product and the sum are SEPARATE STATEMENTS.** numpy performs them as two
///    array operations, so the result carries two roundings. Written as one expression
///    `i * step + start`, a compiler with `-ffp-contract=on` may fuse them into an FMA
///    and drop one, which moves the breakpoint by an ulp -- and a breakpoint is what
///    `locate` compares against, so the displacement becomes a changed verdict rather
///    than a changed value. `design/backend_parity.md` Rule 11.
///
/// \tparam T The scalar type.
/// \param bounds `(ndim, 2)` row-major per-axis `[lo, hi]` pairs.
/// \param cells Per-axis cell counts, length `ndim`, each `>= 1`.
/// \return The uniform grid.
/// \throws std::invalid_argument If `bounds` has fewer than one row or not two
///         columns, `cells` has the wrong length, any count is `< 1`, or any axis has
///         `lo >= hi`.
template <class T>
[[nodiscard]] TensorProductGrid<T> uniform_grid(span2d<const T> bounds,
                                                std::span<const std::int64_t> cells) {
    using pantr::value_of;
    const std::size_t ndim = bounds.extent(0);
    if (bounds.extent(1) != 2) {
        throw std::invalid_argument("uniform_grid: bounds must have shape (ndim, 2); got ("
                                    + std::to_string(ndim) + ", "
                                    + std::to_string(bounds.extent(1)) + ").");
    }
    if (ndim < 1) {
        throw std::invalid_argument("uniform_grid: ndim must be >= 1; got 0.");
    }
    if (cells.size() != ndim) {
        throw std::invalid_argument("uniform_grid: cells must be a scalar or a length-"
                                    + std::to_string(ndim) + " sequence; got length "
                                    + std::to_string(cells.size()) + ".");
    }
    for (const std::int64_t c : cells) {
        if (c < 1) {
            throw std::invalid_argument("uniform_grid: every cells entry must be >= 1; got "
                                        + std::to_string(c) + ".");
        }
    }
    std::vector<std::vector<T>> breakpoints(ndim);
    for (std::size_t d = 0; d < ndim; ++d) {
        const T start = at(bounds, d, std::size_t{0});
        const T stop = at(bounds, d, std::size_t{1});
        if (!(value_of(start) < value_of(stop))) {
            throw std::invalid_argument(
                "uniform_grid: bounds must satisfy lo < hi on every axis; axis "
                + std::to_string(d) + " does not.");
        }
        const auto count = static_cast<std::size_t>(cells[d]);
        const T div = static_cast<T>(cells[d]);
        const T delta = stop - start;
        const T step = delta / div;
        std::vector<T>& axis = breakpoints[d];
        axis.resize(count + 1);
        const bool step_underflowed = value_of(step) == 0;
        for (std::size_t i = 0; i <= count; ++i) {
            const T index = static_cast<T>(i);
            T scaled{};
            if (step_underflowed) {
                const T quotient = index / div;
                scaled = quotient * delta;
            } else {
                scaled = index * step;
            }
            axis[i] = scaled + start;
        }
        axis[count] = stop;
    }
    return TensorProductGrid<T>(breakpoints);
}

}  // namespace pantr::grid
