"""Tensor-product grid with per-axis breakpoint vectors.

:class:`TensorProductGrid` is the first-class concrete :class:`pantr.grid.Grid`:
a tensor product of axis-aligned boxes, stored as one strictly-increasing
breakpoint array per axis. A cell is addressed by a flat row-major (C-order)
identifier; see :mod:`pantr.grid._cell_index` for the convention, which matches
:class:`pantr.bspline.SpanwiseElementExtraction` so a grid and an extraction
operator built on the same :class:`pantr.bspline.BsplineSpace` agree on cell ids.

Two classes, and the split is the port
--------------------------------------

:class:`TensorProductGrid` is a **wrapper**. Since the 2026-08-27 amendment to
``design/cross_backend_types.md`` the grid itself is owned by the C++ core
(``cpp/include/pantr/grid/tensor_product_grid.hpp``) and this class holds one.
Ownership moved rather than being duplicated: there is one implementation of a
tensor-product grid and one Python class in front of it, which keeps every
``isinstance`` site across the package working unchanged.

``_TensorProductGridPython`` is what that class used to be, renamed. It is the
port's parity oracle and the implementation :func:`_impl_class` selects under
``PANTR_BACKEND=python``, and it is temporary.

Footprint
---------

The grid stores only the per-axis breakpoints (total size
``sum_k (cells_per_axis[k] + 1)``) plus a handful of small metadata arrays. It
never materializes per-cell bounds or connectivity -- those are computed on
demand. The only ``O(num_cells)`` structure, the :class:`pantr.grid.BVH` behind
:meth:`~pantr.grid.Grid.query_aabb`, is built lazily on first query, so a grid
used purely for geometry (the common case for a B-spline knot grid) stays
proportional to the breakpoints, not to the cell count.

The breakpoints are packed into the flat layout the batch point-location kernel
consumes **once, at construction**, in both implementations. They used to be
repacked -- a concatenate plus three arrays -- on every ``locate_many`` call.

Construction
------------

- ``TensorProductGrid(breakpoints)`` -- from explicit per-axis breakpoint arrays.
- :func:`uniform_grid` -- a uniform grid on a bounding box with given per-axis
  cell counts.
- :func:`tensor_product_grid` -- the knot-span grid of a
  :class:`pantr.bspline.BsplineSpace` (its per-axis unique in-domain knots).
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING, Any, Final

import numpy as np

from .._numba_compat import wait_for_jit_warmup
from ._cell_index import c_order_strides, flat_to_multi, multi_to_flat
from ._grid import GridRestriction, _GridPython, _GridWrapper
from ._grid_backend import locate_points_kernel
from ._grid_utils import (
    _as_float64,
    _mask_nonfinite_locate,
    _normalize_point,
    _python_backend_selected,
)

if TYPE_CHECKING:
    from collections.abc import Sequence

    import numpy.typing as npt

    from .._pantr_cpp import TensorProductGrid as _CppTensorProductGrid
    from ..bspline import BsplineSpace
    from ._tags import CellTags, FacetTags

_EPS: Final[float] = float(np.finfo(np.float64).eps)
"""Double-precision machine epsilon, the unit the tolerance below is stated in."""

_UNIFORM_SPACING_EPS_FACTOR: Final[int] = 16
"""Multiple of ``eps`` that :attr:`TensorProductGrid.is_uniform` allows spacings to differ by.

**Relative to the coordinate scale**, not absolute, and that is a correction rather
than a transliteration. This replaced a bare ``1e-10`` whose stated rationale was cell
count -- *"chosen so a 1e6-cell uniform grid still registers as uniform"* -- which is
wrong in both halves: the spread of the spacings does not grow with the cell count and
does grow with the coordinate magnitude. Measured on this tree,
``uniform_grid([[1e6, 1e6 + 1]], 100)``, an exact ``linspace`` grid, reported
``is_uniform == False`` under the old constant, while a grid on ``[0, 1e-12]`` passed
whatever its spacing.

The derivation. Let an axis run from ``a`` to ``b`` over ``n`` cells, generated by
:func:`numpy.linspace`, write ``u = eps / 2`` for the unit roundoff, and let
``S = |a| + |b|``, which dominates both the largest coordinate and the extent. The
generated breakpoint is ``x_i = fl(fl(i * fl(fl(b - a) / n)) + a)``: the difference, the
division, the product and the sum each round once, the first three of quantities bounded
by ``|b - a| <= S`` and the fourth of one bounded by ``max(|a|, |b|) <= S``. So
``|x_i - (a + i (b - a) / n)| <= 4 u S`` to first order. A stored spacing
``d_i = fl(x_{i+1} - x_i)`` adds one more rounding of a quantity no larger than ``S``,
giving ``|d_i - (b - a) / n| <= 9 u S``, and the spread of the spacings is at most twice
that: ``ptp(d) <= 18 u S = 9 eps S``. **There is no ``n`` in the bound.**

Rounded up to the next power of two, ``16 eps``: a margin of 1.8 over the derivation.
Measured over 200000 random ``linspace`` axes spanning forty decades of magnitude, the
largest observed ``ptp(d) / (eps S)`` was 2.74, so the constant also carries a factor of
5.8 over anything seen.

Where it degrades: ``16 eps S`` underflows to zero for ``S`` below about ``1e-292``,
where the test becomes exact equality of the spacings. That is the honest answer at that
scale rather than a failure -- every coordinate there is subnormal, and a tolerance
smaller than the smallest subnormal cannot be represented to compare against.

The C++ grid carries the same constant and the same derivation as
``pantr::grid::kUniformSpacingEpsFactor``; ``tests/parity/test_grid_types.py`` asserts
the two agree.
"""

_MIN_BREAKPOINTS_PER_AXIS: Final[int] = 2
"""Smallest useful grid: at least one cell per axis (two breakpoints)."""


def _axis_is_uniform(bp: npt.NDArray[np.float64]) -> bool:
    """Report whether one axis's breakpoint spacings are constant.

    Constant to within :data:`_UNIFORM_SPACING_EPS_FACTOR` times ``eps`` times the
    axis's coordinate scale; see that constant for the derivation.

    Args:
        bp (npt.NDArray[np.float64]): One axis's strictly increasing breakpoints.

    Returns:
        bool: ``True`` iff the spacings agree within the tolerance. An axis of one
        cell has no two spacings to compare and is uniform by definition.
    """
    if bp.shape[0] <= _MIN_BREAKPOINTS_PER_AXIS:
        return True
    scale = abs(float(bp[0])) + abs(float(bp[-1]))
    return bool(np.ptp(np.diff(bp)) <= _UNIFORM_SPACING_EPS_FACTOR * _EPS * scale)


def _validated_breakpoints(
    breakpoints: Sequence[npt.ArrayLike],
) -> list[npt.NDArray[np.float64]]:
    """Coerce per-axis breakpoint array-likes to contiguous ``float64`` arrays.

    Coercion only. Whether the values are usable -- at least two of them, finite, and
    strictly increasing -- is the implementation's to decide and to report, in whichever
    language it is written; this is the ``ArrayLike`` half that stays in Python because
    it is about Python's calling convention rather than about grids.

    Args:
        breakpoints (Sequence[npt.ArrayLike]): One array-like per axis.

    Returns:
        list[npt.NDArray[np.float64]]: One C-contiguous 1-D ``float64`` array per axis.

    Raises:
        TypeError: If any axis has a non-numeric dtype or cannot become an ndarray.
    """
    return [
        np.ascontiguousarray(_as_float64(bp, name=f"breakpoints[{d}]").ravel())
        for d, bp in enumerate(breakpoints)
    ]


class _TensorProductGridPython(_GridPython):
    """The Python tensor-product grid, and the port's parity oracle.

    What :class:`TensorProductGrid` was before the grid moved to C++, renamed. It is
    a complete :class:`pantr.grid.Grid` on its own and is the implementation held
    under ``PANTR_BACKEND=python``.

    Cells are numbered in row-major (C) order over :attr:`cells_per_axis` (last
    axis varies fastest).

    Scaffolding: it exists to be the thing the C++ grid is compared against, and
    "keep parity with this class" is never a reason not to improve the C++.

    Attributes:
        _ndim (int): Number of axes.
        _breakpoints (tuple[npt.NDArray[np.float64], ...]): Read-only per-axis
            breakpoints.
        _cells_per_axis (tuple[int, ...]): Per-axis cell counts.
        _num_cells (int): Product of the per-axis cell counts.
        _bounds (npt.NDArray[np.float64]): Read-only ``(ndim, 2)`` extremes.
        _strides (npt.NDArray[np.int64]): Read-only per-axis C-order flat strides.
        _is_uniform (bool): Whether every axis is uniformly spaced.
        _knots_flat (npt.NDArray[np.float64]): Every axis's breakpoints end to end,
            the layout the batch location kernel consumes.
        _knot_starts (npt.NDArray[np.int64]): Per-axis offset into ``_knots_flat``.
        _cells_per_axis_arr (npt.NDArray[np.int64]): ``_cells_per_axis`` as an array,
            for the same kernel.
    """

    __slots__ = (
        "_bounds",
        "_breakpoints",
        "_cells_per_axis",
        "_cells_per_axis_arr",
        "_is_uniform",
        "_knot_starts",
        "_knots_flat",
        "_ndim",
        "_num_cells",
        "_strides",
    )

    def __init__(self, breakpoints: Sequence[npt.ArrayLike]) -> None:
        """Build a tensor-product grid from per-axis breakpoint vectors.

        Args:
            breakpoints (Sequence[npt.ArrayLike]): One strictly increasing
                ``float64`` array-like per axis, each of length
                ``cells_per_axis[d] + 1 >= 2``.

        Raises:
            ValueError: If ``breakpoints`` is empty, any axis has fewer than two
                entries, or any axis is non-finite or not strictly increasing.
            TypeError: If a breakpoint array cannot be cast to ``float64``.
        """
        super().__init__()
        ndim = len(breakpoints)
        if ndim < 1:
            raise ValueError(f"TensorProductGrid needs at least one axis; got {ndim}.")
        validated: list[npt.NDArray[np.float64]] = []
        cells_per_axis: list[int] = []
        for d, bp in enumerate(breakpoints):
            arr = _as_float64(bp, name=f"breakpoints[{d}]").ravel()
            if arr.shape[0] < _MIN_BREAKPOINTS_PER_AXIS:
                raise ValueError(
                    f"breakpoints[{d}] must have at least {_MIN_BREAKPOINTS_PER_AXIS} entries "
                    f"(>= 1 cell); got shape {arr.shape}."
                )
            if not np.all(np.isfinite(arr)):
                raise ValueError(f"breakpoints[{d}] must contain only finite values.")
            if not np.all(np.diff(arr) > 0.0):
                raise ValueError(f"breakpoints[{d}] must be strictly increasing.")
            frozen = np.ascontiguousarray(arr.copy(), dtype=np.float64)
            frozen.flags.writeable = False
            validated.append(frozen)
            cells_per_axis.append(int(frozen.shape[0]) - 1)
        self._ndim = ndim
        self._breakpoints = tuple(validated)
        self._cells_per_axis = tuple(cells_per_axis)
        self._num_cells = math.prod(self._cells_per_axis)
        bounds = np.empty((ndim, 2), dtype=np.float64)
        for d in range(ndim):
            bounds[d, 0] = self._breakpoints[d][0]
            bounds[d, 1] = self._breakpoints[d][-1]
        bounds.flags.writeable = False
        self._bounds = bounds
        self._strides = c_order_strides(self._cells_per_axis)
        self._strides.flags.writeable = False
        self._is_uniform = all(_axis_is_uniform(bp) for bp in self._breakpoints)
        # The kernel's flat layout, built once. Nothing about it depends on the query,
        # so rebuilding it per call -- which this class used to do -- was a concatenate
        # and three allocations spent on every batch location.
        counts = np.array([bp.shape[0] for bp in self._breakpoints], dtype=np.int64)
        knot_starts = np.zeros(ndim, dtype=np.int64)
        knot_starts[1:] = np.cumsum(counts[:-1])
        knot_starts.flags.writeable = False
        self._knot_starts = knot_starts
        knots_flat = np.ascontiguousarray(np.concatenate(self._breakpoints), dtype=np.float64)
        knots_flat.flags.writeable = False
        self._knots_flat = knots_flat
        cells_arr = np.array(self._cells_per_axis, dtype=np.int64)
        cells_arr.flags.writeable = False
        self._cells_per_axis_arr = cells_arr

    # ------------------------------------------------------------------
    # Read-only attributes
    # ------------------------------------------------------------------

    @property
    def ndim(self) -> int:
        """Get the spatial dimension of the grid.

        Returns:
            int: Number of axes (``>= 1``).
        """
        return self._ndim

    @property
    def num_cells(self) -> int:
        """Get the total number of cells.

        Returns:
            int: Product of the per-axis cell counts.
        """
        return self._num_cells

    @property
    def cells_per_axis(self) -> tuple[int, ...]:
        """Get the per-axis cell counts.

        Returns:
            tuple[int, ...]: Length-``ndim`` tuple of per-axis counts.
        """
        return self._cells_per_axis

    @property
    def breakpoints(self) -> tuple[npt.NDArray[np.float64], ...]:
        """Get the per-axis strictly increasing breakpoint arrays.

        Returns:
            tuple[npt.NDArray[np.float64], ...]: Read-only ``float64`` arrays;
            ``breakpoints[d]`` has length ``cells_per_axis[d] + 1``.
        """
        return self._breakpoints

    @property
    def bounds(self) -> npt.NDArray[np.float64]:
        """Get the per-axis ``[lo, hi]`` extremes.

        Returns:
            npt.NDArray[np.float64]: Read-only ``(ndim, 2)`` array.
        """
        return self._bounds

    @property
    def is_uniform(self) -> bool:
        """Get whether every axis has uniform breakpoint spacing.

        Returns:
            bool: ``True`` iff each axis's spacing is constant to within the
            scale-relative tolerance :data:`_UNIFORM_SPACING_EPS_FACTOR` states.
        """
        return self._is_uniform

    # ------------------------------------------------------------------
    # Index helpers (row-major C-order)
    # ------------------------------------------------------------------

    def cell_multi_index(self, cid: int) -> tuple[int, ...]:
        """Return the per-axis indices ``(i_0, ..., i_{ndim-1})`` of cell ``cid``.

        Args:
            cid (int): Flat cell identifier.

        Returns:
            tuple[int, ...]: Length-``ndim`` per-axis index tuple (C-order).

        Raises:
            IndexError: If ``cid`` is out of range.
        """
        return flat_to_multi(int(cid), self._cells_per_axis)

    def flat_cell_index(self, multi: Sequence[int]) -> int:
        """Map per-axis cell indices to the flat cell identifier (C-order).

        Args:
            multi (Sequence[int]): Length-``ndim`` per-axis indices; each entry
                must satisfy ``0 <= i_k < cells_per_axis[k]``.

        Returns:
            int: Flat cell identifier.

        Raises:
            ValueError: If ``len(multi) != ndim``.
            IndexError: If any per-axis index is out of range.
        """
        return multi_to_flat(multi, self._cells_per_axis)

    # ------------------------------------------------------------------
    # Grid contract overrides
    # ------------------------------------------------------------------

    def cell_bounds(
        self,
        cid: int,
    ) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
        """Return cell ``cid``'s axis-aligned ``(lo, hi)`` corners.

        Args:
            cid (int): Cell identifier.

        Returns:
            tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: Fresh,
            writeable length-``ndim`` ``float64`` arrays.

        Raises:
            IndexError: If ``cid`` is out of range.
        """
        multi = self.cell_multi_index(cid)
        lo = np.empty(self._ndim, dtype=np.float64)
        hi = np.empty(self._ndim, dtype=np.float64)
        for d, i in enumerate(multi):
            lo[d] = self._breakpoints[d][i]
            hi[d] = self._breakpoints[d][i + 1]
        return lo, hi

    def locate(self, pt: npt.ArrayLike) -> int | None:
        """Return the cell containing ``pt``, or ``None`` if ``pt`` is outside.

        A point exactly on an interior breakpoint is assigned to the
        lower-indexed cell sharing that face; a point on the outer boundary is
        assigned to the adjacent boundary cell.  Non-finite coordinates
        (NaN or infinity) are outside every cell.

        Args:
            pt (npt.ArrayLike): Length-``ndim`` point.

        Returns:
            int | None: Containing cell id, or ``None`` when ``pt`` lies outside
            the grid domain.

        Raises:
            ValueError: If ``pt`` does not have length ``ndim``.
        """
        arr = _normalize_point(pt, self._ndim)
        cid = 0
        for d in range(self._ndim):
            bp = self._breakpoints[d]
            x = float(arr[d])
            # The negated chained comparison is NaN-safe (NaN fails both bounds).
            if not bp[0] <= x <= bp[-1]:
                return None
            idx = int(np.searchsorted(bp, x, side="left")) - 1
            idx = min(max(idx, 0), self._cells_per_axis[d] - 1)
            cid += idx * int(self._strides[d])
        return cid

    def locate_many(self, points: npt.ArrayLike) -> npt.NDArray[np.int64]:
        """Locate a batch of points via the Numba per-axis search kernel.

        The kernel's flat descriptor arrays were packed at construction; this method
        allocates only the output.

        Args:
            points (npt.ArrayLike): ``(npts, ndim)`` array-like of points, or a
                single length-``ndim`` point.

        Returns:
            npt.NDArray[np.int64]: Shape ``(npts,)`` cell ids; ``-1`` for points
            outside the grid (including points with NaN or infinite coordinates).

        Raises:
            ValueError: If the trailing axis of ``points`` is not ``ndim``.
        """
        pts = self._normalize_points(points)
        out = np.empty(pts.shape[0], dtype=np.int64)
        # The Numba kernel behind this is ``parallel=True`` and the import-time
        # warmup compiles on a background thread; Numba's workqueue layer aborts
        # the process rather than raising if a parallel call races it.
        wait_for_jit_warmup()
        locate_points_kernel()(
            pts,
            self._knots_flat,
            self._knot_starts,
            self._cells_per_axis_arr,
            self._strides,
            out,
        )
        _mask_nonfinite_locate(pts, out)
        return out

    def neighbor_across_facet(self, cid: int, lfid: int) -> int | None:
        """Return the cell across local facet ``lfid`` of ``cid``, or ``None``.

        Uses the ``lfid = 2 * axis + side`` encoding and per-axis arithmetic.

        Args:
            cid (int): Cell identifier.
            lfid (int): Local facet identifier in ``[0, 2 * ndim)``.

        Returns:
            int | None: Neighbouring cell id, or ``None`` on a boundary facet.

        Raises:
            IndexError: If ``cid`` or ``lfid`` is out of range.
        """
        self._check_lfid(cid, lfid)
        axis, side = divmod(int(lfid), 2)
        multi = list(self.cell_multi_index(cid))
        i = multi[axis]
        if side == 0:
            if i == 0:
                return None
            multi[axis] = i - 1
        else:
            if i == self._cells_per_axis[axis] - 1:
                return None
            multi[axis] = i + 1
        return self.flat_cell_index(multi)

    def collect_cell_bounds(
        self,
    ) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
        """Materialize per-cell ``(lo, hi)`` in C-order via per-axis broadcasting.

        Returns:
            tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
            ``(cell_lo, cell_hi)`` of shape ``(num_cells, ndim)`` in cell-id
            order.
        """
        lo_axes = [bp[:-1] for bp in self._breakpoints]
        hi_axes = [bp[1:] for bp in self._breakpoints]
        idx_grids = np.meshgrid(*[np.arange(n) for n in self._cells_per_axis], indexing="ij")
        cell_lo = np.empty((self._num_cells, self._ndim), dtype=np.float64)
        cell_hi = np.empty((self._num_cells, self._ndim), dtype=np.float64)
        for d in range(self._ndim):
            flat_idx = idx_grids[d].ravel()
            cell_lo[:, d] = lo_axes[d][flat_idx]
            cell_hi[:, d] = hi_axes[d][flat_idx]
        return cell_lo, cell_hi

    def restrict(self, cell_ids: npt.ArrayLike) -> GridRestriction:
        """Return the multi-index bounding-box sub-grid spanning ``cell_ids``.

        The window is the axis-aligned bounding box of the requested cells in
        multi-index space. Each axis of the sub-grid uses a pure slice of this
        grid's breakpoints, ``breakpoints[d][imin_d : imax_d + 2]`` -- never
        re-based or re-clamped -- so the sub-grid's cells coincide exactly with
        the matching cells of this grid.

        Args:
            cell_ids (npt.ArrayLike): Flat cell identifiers to span; duplicates
                are ignored. Each must satisfy ``0 <= cid < num_cells``.

        Returns:
            GridRestriction: The windowed sub-grid, its ``local_to_global_cell``
            map of shape ``(sub.num_cells,)``, and the ``in_subset`` mask flagging
            requested versus bounding-box-fill cells. The sub-grid is this same
            implementation class; the wrapper in front puts it back in a
            :class:`TensorProductGrid`.

        Raises:
            ValueError: If ``cell_ids`` is empty.
            IndexError: If any cell id is out of range ``[0, num_cells)``.
            TypeError: If ``cell_ids`` is not integer-valued.
        """
        ids = np.asarray(cell_ids).ravel()
        if ids.size == 0:
            raise ValueError("restrict: cell_ids must be non-empty.")
        if not np.issubdtype(ids.dtype, np.integer):
            raise TypeError(f"restrict: cell_ids must be integer-valued; got dtype {ids.dtype}.")
        ids = ids.astype(np.int64, copy=False)
        lo, hi = int(ids.min()), int(ids.max())
        if lo < 0 or hi >= self._num_cells:
            raise IndexError(
                f"restrict: cell id out of range [0, {self._num_cells}); got [{lo}, {hi}]."
            )
        multi = np.unravel_index(ids, self._cells_per_axis)
        imin = [int(m.min()) for m in multi]
        imax = [int(m.max()) for m in multi]
        sub_breakpoints = [self._breakpoints[d][imin[d] : imax[d] + 2] for d in range(self._ndim)]
        sub_grid = _TensorProductGridPython(sub_breakpoints)
        sub_cells_per_axis = [imax[d] - imin[d] + 1 for d in range(self._ndim)]
        idx_grids = np.meshgrid(
            *[np.arange(n, dtype=np.int64) for n in sub_cells_per_axis], indexing="ij"
        )
        local_to_global = np.zeros(int(math.prod(sub_cells_per_axis)), dtype=np.int64)
        for d in range(self._ndim):
            local_to_global += (idx_grids[d].ravel() + imin[d]) * int(self._strides[d])
        in_subset = np.isin(local_to_global, ids)
        local_to_global.flags.writeable = False
        in_subset.flags.writeable = False
        return GridRestriction(sub_grid, local_to_global, in_subset)

    def __repr__(self) -> str:
        """Return a compact representation useful for debugging.

        It names the public class rather than this one: this class is what that one
        holds, and a caller printing a grid should not be told which backend built it.

        Returns:
            str: ``"TensorProductGrid(ndim=..., cells_per_axis=..., uniform=...)"``.
        """
        return (
            f"TensorProductGrid(ndim={self._ndim}, cells_per_axis={self._cells_per_axis}, "
            f"uniform={self._is_uniform})"
        )


def _impl_class() -> type[_TensorProductGridPython] | type[_CppTensorProductGrid]:
    """The implementation class the active backend selects.

    The choice is per process rather than per instance, for the reason
    :func:`pantr.grid._grid_utils._python_backend_selected` gives at length. It bites
    harder here than for the value types: ``restrict`` returns a grid, so a per-instance
    choice would let a sub-grid cross implementations, which is exactly the
    reconciliation ``design/cross_backend_types.md`` forbids.

    Returns:
        type[_TensorProductGridPython] | type[_CppTensorProductGrid]: The oracle
        under the Python backend, the bound C++ class otherwise.

    Raises:
        RuntimeError: If the C++ backend is requested and is not available.
    """
    if _python_backend_selected():
        return _TensorProductGridPython
    from pantr import _pantr_cpp  # noqa: PLC0415  (optional, imported only when selected)

    return _pantr_cpp.TensorProductGrid


def _rebuild_tensor_product_grid(
    breakpoints: tuple[npt.NDArray[np.float64], ...],
    cell_tags: CellTags | None,
    facet_tags: FacetTags | None,
) -> TensorProductGrid:
    """Rebuild a pickled grid from its breakpoints and its tags.

    The reconstruction :meth:`TensorProductGrid.__reduce__` names. A module-level
    function rather than a ``__setstate__``, because the grid is immutable once built
    and the tags are replayed through the public :meth:`~pantr.grid.CellTags.set`
    rather than written into it.

    Args:
        breakpoints (tuple[npt.NDArray[np.float64], ...]): The per-axis breakpoints.
        cell_tags (CellTags | None): The cell registry to replay, or ``None`` if the
            pickled grid had none -- which is what keeps the memo slots lazy across a
            round trip.
        facet_tags (FacetTags | None): The facet registry to replay, or ``None``.

    Returns:
        TensorProductGrid: The rebuilt grid, in the active backend's implementation.
    """
    grid = TensorProductGrid(breakpoints)
    if cell_tags is not None:
        for name in cell_tags.names:
            ids, values = cell_tags[name]
            grid.cell_tags.set(name, ids, values)
    if facet_tags is not None:
        for name in facet_tags.names:
            keys, values = facet_tags[name]
            grid.facet_tags.set(name, keys, values)
    return grid


class TensorProductGrid(_GridWrapper):
    """Tensor-product grid of axis-aligned boxes with per-axis breakpoints.

    Cells are numbered in row-major (C) order over :attr:`cells_per_axis` (last
    axis varies fastest). See the module docstring for the footprint and
    construction notes. Size and geometry metadata are exposed through the
    :attr:`ndim`, :attr:`num_cells`, :attr:`cells_per_axis`, :attr:`breakpoints`,
    and :attr:`bounds` properties.

    **This class is a wrapper.** The grid itself is owned by the C++ core and this
    class holds one; under ``PANTR_BACKEND=python`` the thing held is
    ``_TensorProductGridPython`` instead, which is the port's oracle and is
    temporary. Everything a :class:`pantr.grid.Grid` can do is forwarded by
    ``_GridWrapper``; what is defined here is this grid's own surface plus the four
    things a generic forwarder cannot supply -- the constructor, the ``repr``, the
    pickle, and the refusal to be mutated.

    Instances are immutable apart from the two tag registries, which accumulate, and
    the three memoized handles in front of them.

    Attributes:
        _impl (Any): The grid this wrapper forwards to; see :func:`_impl_class`.
        _bvh (BVH | None): Memoized spatial index; ``None`` until first built.
        _cell_tags (CellTags | None): Memoized cell-tag registry; ``None`` until
            first use.
        _facet_tags (FacetTags | None): Memoized facet-tag registry; ``None`` until
            first use.
    """

    __slots__ = ("_bvh", "_cell_tags", "_facet_tags", "_impl")

    def __init__(self, breakpoints: Sequence[npt.ArrayLike]) -> None:
        """Build a tensor-product grid from per-axis breakpoint vectors.

        Args:
            breakpoints (Sequence[npt.ArrayLike]): One strictly increasing
                ``float64`` array-like per axis, each of length
                ``cells_per_axis[d] + 1 >= 2``.

        Raises:
            ValueError: If ``breakpoints`` is empty, any axis has fewer than two
                entries, or any axis is non-finite or not strictly increasing.
            TypeError: If a breakpoint array cannot be cast to ``float64``.
        """
        self._take(_impl_class()(_validated_breakpoints(breakpoints)))

    @classmethod
    def _wrap(cls, impl: _TensorProductGridPython | _CppTensorProductGrid) -> TensorProductGrid:
        """Wrap an implementation object that is already valid.

        Args:
            impl (_TensorProductGridPython | _CppTensorProductGrid): The
                implementation to adopt, typically the sub-grid an implementation's
                own ``restrict`` produced.

        Returns:
            TensorProductGrid: A wrapper around ``impl``, with no re-validation.
        """
        self = object.__new__(cls)
        self._take(impl)
        return self

    def _take(self, impl: _TensorProductGridPython | _CppTensorProductGrid) -> None:
        """Hold an implementation, with the three memo slots cleared.

        One place rather than two, so that neither construction path can leave a slot
        uninitialised -- which surfaces as a bare ``AttributeError`` from inside a
        property, a long way from the constructor that skipped it.

        Args:
            impl (_TensorProductGridPython | _CppTensorProductGrid): The
                implementation to hold.
        """
        object.__setattr__(self, "_impl", impl)
        object.__setattr__(self, "_bvh", None)
        object.__setattr__(self, "_cell_tags", None)
        object.__setattr__(self, "_facet_tags", None)

    def __setattr__(self, name: str, value: object) -> None:
        """Reject post-construction attribute writes.

        Args:
            name (str): The attribute being set.
            value (object): The value it would take.

        Raises:
            AttributeError: Always. The grid is immutable once built, and the memo
                slots are written through ``object.__setattr__``.
        """
        raise AttributeError(f"TensorProductGrid is immutable; cannot set attribute {name!r}.")

    def __delattr__(self, name: str) -> None:
        """Reject attribute deletion.

        Args:
            name (str): The attribute being deleted.

        Raises:
            AttributeError: Always.
        """
        raise AttributeError(f"TensorProductGrid is immutable; cannot delete attribute {name!r}.")

    def __reduce__(self) -> tuple[Any, tuple[Any, ...]]:
        """Pickle by the breakpoints and the tags, never by the implementation.

        The C++ handle is not picklable and must not become part of the wire format:
        a pickle written under one backend has to load under the other, or the
        backend switch would silently become a data-format switch.

        The tags travel because they are the grid's state rather than a cache -- a
        grid that lost its in/out classification on a round trip would be a data loss,
        not a performance one. The memoized BVH does not: it is rebuilt from the
        breakpoints in one call, and shipping ``O(num_cells)`` node arrays to avoid
        recomputing them would trade a large pickle for a small saving. The two
        registries are read from the memo slots rather than through the properties, so
        pickling an untagged grid does not materialize one and the slots stay lazy on
        the far side too.

        Returns:
            tuple: :func:`_rebuild_tensor_product_grid` and the arguments to replay.
        """
        cells = self._cell_tags
        facets = self._facet_tags
        return (
            _rebuild_tensor_product_grid,
            (
                self.breakpoints,
                cells if cells is not None and len(cells) > 0 else None,
                facets if facets is not None and len(facets) > 0 else None,
            ),
        )

    def __repr__(self) -> str:
        """Return a compact representation useful for debugging.

        Formatted here rather than by the implementation, so that the two backends
        print identically whatever their own formatting conventions are.

        Returns:
            str: ``"TensorProductGrid(ndim=..., cells_per_axis=..., uniform=...)"``.
        """
        return (
            f"TensorProductGrid(ndim={self.ndim}, cells_per_axis={self.cells_per_axis}, "
            f"uniform={self.is_uniform})"
        )

    # ------------------------------------------------------------------
    # This grid's own surface
    # ------------------------------------------------------------------

    @property
    def cells_per_axis(self) -> tuple[int, ...]:
        """Get the per-axis cell counts.

        Returns:
            tuple[int, ...]: Length-``ndim`` tuple of per-axis counts.
        """
        return tuple(int(n) for n in self._impl.cells_per_axis)

    @property
    def breakpoints(self) -> tuple[npt.NDArray[np.float64], ...]:
        """Get the per-axis strictly increasing breakpoint arrays.

        Returns:
            tuple[npt.NDArray[np.float64], ...]: Read-only ``float64`` arrays;
            ``breakpoints[d]`` has length ``cells_per_axis[d] + 1``. Under the C++
            backend these are views into the grid's own storage rather than copies,
            so reading them costs nothing and writing to them is refused.
        """
        return tuple(self._impl.breakpoints)

    @property
    def bounds(self) -> npt.NDArray[np.float64]:
        """Get the per-axis ``[lo, hi]`` extremes.

        Frozen here rather than by the implementation: the wrapper owns
        read-only-ness for every array it hands out, which is the same rule that
        freezes :meth:`~pantr.grid.Grid.boundary_facets`.

        Returns:
            npt.NDArray[np.float64]: Read-only ``(ndim, 2)`` array.
        """
        bounds: npt.NDArray[np.float64] = self._impl.bounds
        bounds.flags.writeable = False
        return bounds

    @property
    def is_uniform(self) -> bool:
        """Get whether every axis has uniform breakpoint spacing.

        Returns:
            bool: ``True`` iff each axis's spacing is constant to within the
            scale-relative tolerance :data:`_UNIFORM_SPACING_EPS_FACTOR` states.
        """
        return bool(self._impl.is_uniform)

    def cell_multi_index(self, cid: int) -> tuple[int, ...]:
        """Return the per-axis indices ``(i_0, ..., i_{ndim-1})`` of cell ``cid``.

        Args:
            cid (int): Flat cell identifier.

        Returns:
            tuple[int, ...]: Length-``ndim`` per-axis index tuple (C-order).

        Raises:
            IndexError: If ``cid`` is out of range.
        """
        return tuple(int(i) for i in self._impl.cell_multi_index(int(cid)))

    def flat_cell_index(self, multi: Sequence[int]) -> int:
        """Map per-axis cell indices to the flat cell identifier (C-order).

        Args:
            multi (Sequence[int]): Length-``ndim`` per-axis indices; each entry
                must satisfy ``0 <= i_k < cells_per_axis[k]``.

        Returns:
            int: Flat cell identifier.

        Raises:
            ValueError: If ``len(multi) != ndim``.
            IndexError: If any per-axis index is out of range.
            TypeError: If ``multi`` is not integer-valued.
        """
        indices = np.asarray(multi)
        # Checked here because there is no `std::exception` nanobind turns into a
        # `TypeError`, and because a silent truncation of `[0.5, 1.5]` to `[0, 1]`
        # returns a plausible cell id rather than an error.
        if indices.size > 0 and not np.issubdtype(indices.dtype, np.integer):
            raise TypeError(
                f"flat_cell_index: multi must be integer-valued; got dtype {indices.dtype}."
            )
        return int(self._impl.flat_cell_index(np.ascontiguousarray(indices, dtype=np.int64)))


def uniform_grid(
    bounds: npt.ArrayLike,
    cells: int | Sequence[int],
) -> TensorProductGrid:
    """Build a uniform :class:`TensorProductGrid` on a bounding box.

    Args:
        bounds (npt.ArrayLike): ``(ndim, 2)`` array-like of per-axis
            ``[lo, hi]`` pairs with ``ndim >= 1``.
        cells (int | Sequence[int]): Number of cells per axis. A scalar is
            broadcast to every axis; a length-``ndim`` sequence gives per-axis
            counts. Each count must be ``>= 1``.

    Returns:
        TensorProductGrid: A uniform tensor-product grid.

    Raises:
        ValueError: If ``bounds`` does not have shape ``(ndim, 2)``, any axis has
            ``lo >= hi``, ``cells`` has the wrong length, or any count is ``< 1``.
        TypeError: If ``bounds`` cannot be cast to ``float64``.
    """
    arr = _as_float64(bounds, name="bounds")
    if arr.ndim != 2 or arr.shape[-1] != 2:  # noqa: PLR2004
        raise ValueError(f"uniform_grid: bounds must have shape (ndim, 2); got {arr.shape}.")
    ndim = int(arr.shape[0])
    if ndim < 1:
        raise ValueError(f"uniform_grid: ndim must be >= 1; got {ndim}.")
    if not np.all(arr[:, 0] < arr[:, 1]):
        raise ValueError(
            f"uniform_grid: bounds must satisfy lo < hi on every axis; got {arr.tolist()!r}."
        )
    cells_tuple = (int(cells),) * ndim if isinstance(cells, int) else tuple(int(c) for c in cells)
    if len(cells_tuple) != ndim:
        raise ValueError(
            f"uniform_grid: cells must be a scalar or a length-{ndim} sequence; "
            f"got length {len(cells_tuple)}."
        )
    if any(c < 1 for c in cells_tuple):
        raise ValueError(f"uniform_grid: every cells entry must be >= 1; got {cells_tuple!r}.")
    if _impl_class() is _TensorProductGridPython:
        breakpoints = [
            np.linspace(arr[d, 0], arr[d, 1], cells_tuple[d] + 1, dtype=np.float64)
            for d in range(ndim)
        ]
        return TensorProductGrid(breakpoints)
    # The C++ factory reproduces `numpy.linspace`'s sequence bit for bit rather than
    # approximating it; `tests/parity/test_grid_types.py` asserts the two agree exactly
    # across forty decades of coordinate magnitude. Generating the breakpoints here and
    # handing them over would work and would be shorter -- and would mean the C++
    # factory was never reached from Python, which is where that claim would quietly
    # stop being checked.
    from pantr import _pantr_cpp  # noqa: PLC0415  (optional, imported only when selected)

    return TensorProductGrid._wrap(
        _pantr_cpp.uniform_grid(
            np.ascontiguousarray(arr, dtype=np.float64),
            np.ascontiguousarray(cells_tuple, dtype=np.int64),
        )
    )


def tensor_product_grid(space: BsplineSpace) -> TensorProductGrid:
    """Build the knot-span grid of a :class:`pantr.bspline.BsplineSpace`.

    The grid's per-axis breakpoints are the unique in-domain knots of each
    1-D sub-space, so its cells are exactly the space's knot spans and its cell
    ids match :class:`pantr.bspline.SpanwiseElementExtraction` on the same space.

    Args:
        space (BsplineSpace): A tensor-product B-spline space. Periodic
            directions are rejected: a periodic knot vector does not map cleanly
            to a bounded grid.

    Returns:
        TensorProductGrid: A grid whose cells are the knot spans of ``space``.

    Raises:
        ValueError: If any direction of ``space`` is periodic.
    """
    breakpoints: list[npt.NDArray[np.float64]] = []
    for d, sub in enumerate(space.spaces):
        if sub.periodic:
            raise ValueError(
                f"tensor_product_grid: axis {d} is periodic; periodic B-spline spaces "
                "do not map to a bounded tensor-product grid."
            )
        unique, _ = sub.get_unique_knots_and_multiplicity(in_domain=True)
        breakpoints.append(_as_float64(unique, name=f"space.spaces[{d}] unique knots").ravel())
    return TensorProductGrid(breakpoints)


__all__ = ["TensorProductGrid", "tensor_product_grid", "uniform_grid"]
