#!/usr/bin/env python
"""Compare the C++ `HierarchicalGrid`'s refinement half against the Python oracle.

The bindings for this type do not exist yet -- they are the next slice -- so the two
backends cannot be compared through `tests/parity`. This script closes the gap in the
meantime: it drives `src/pantr/grid/_hierarchical_grid.py` over random hierarchies and
random refine/coarsen sequences, replays the same sequences through a self-contained C++
program built against `cpp/include`, and compares everything both sides can answer.

    PYTHONPATH="$(pwd)/src" .venv/bin/python \
        scripts/measure_hierarchical_refinement_parity.py --cases 400

The build directory is only used to find the two header-only dependencies; configure any
preset first, or pass ``--include`` once per extra include directory.

What is compared, and against which criterion
---------------------------------------------

**Exactly**: the cell count, the deepest level, the repr, every cell's level and
multi-index, the whole connectivity table, the vertex count, and a restriction's
``local_to_global_cell`` and ``in_subset``. Every one of them is an integer, an index or a
count, so finite precision does not bite and exact equality is a property of the
mathematics rather than of the build. A tolerance on a cell id would hide a divergence
instead of measuring one, which is `design/backend_parity.md` Rule 11's point: none of the
rules that bound a displacement says anything about a count, and a count is what carries a
verdict.

**To a derived bound**: the exported vertex coordinates. Both sides build a corner as
``b + o * (w / factor ** max_level)``, so the difference between them is bounded by the
same ``2 gamma_2 |x| + 2 gamma_4 |x - b|`` that bounds either against `cell_bounds`. The
script also reports how many coordinates agree **bitwise**, which is an observation and
not the criterion: bit-identity is not a property of the mathematics, and requiring it
would forbid transformations that leave the result correct.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile

import numpy as np

from pantr.grid import TensorProductGrid
from pantr.grid._hierarchical_grid import HierarchicalGrid, hierarchical_grid

# `tests` is a package at the repository root, and running this file directly puts
# `scripts/` on the path rather than the root, so the import below needs the root
# added first. `scripts/measure_bezier_fma_bound.py` imports the same module without
# doing this and cannot be run directly as a result.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from tests._parity_harness import unit_roundoff

_U = unit_roundoff(np.float64)
"""Half an ulp: the relative error of one correctly rounded ``float64`` operation.

Taken from :func:`tests._parity_harness.unit_roundoff` rather than spelled out
again. The quantity is the project's, not this file's, and two spellings of one
bound drift apart the moment either is corrected.
"""


def _gamma(m: float) -> float:
    """Return ``gamma_m = m u / (1 - m u)``.

    Args:
        m (float): The rounding count.

    Returns:
        float: The factor.
    """
    return m * _U / (1.0 - m * _U)


_DRIVER = r"""
// Generated by scripts/measure_hierarchical_refinement_parity.py. Not part of the build.
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <optional>
#include <string>
#include <vector>

#include "pantr/grid/hierarchical_grid.hpp"
#include "pantr/grid/tensor_product_grid.hpp"

using pantr::grid::CellExport;
using pantr::grid::GridRestriction;
using Grid = pantr::grid::HierarchicalGrid<double>;
using Ints = std::vector<std::int64_t>;

constexpr double kUnitRoundoff = 1.1102230246251565e-16;  // eps / 2 for double
constexpr double kGamma2 = 2.0 * kUnitRoundoff / (1.0 - 2.0 * kUnitRoundoff);
constexpr double kGamma4 = 4.0 * kUnitRoundoff / (1.0 - 4.0 * kUnitRoundoff);

int main() {
    std::ios::sync_with_stdio(false);
    std::string token;
    while (std::cin >> token) {
        if (token != "CASE") {
            continue;
        }
        std::int64_t ndim = 0;
        std::cin >> token >> ndim;
        const auto d = static_cast<std::size_t>(ndim);
        Ints factor(d);
        std::cin >> token;
        for (std::size_t k = 0; k < d; ++k) {
            std::cin >> factor[k];
        }
        std::vector<std::vector<double>> breakpoints(d);
        for (std::size_t k = 0; k < d; ++k) {
            std::size_t count = 0;
            std::size_t axis = 0;
            std::cin >> token >> axis >> count;
            breakpoints[axis].resize(count);
            for (std::size_t i = 0; i < count; ++i) {
                std::string value;
                std::cin >> value;
                breakpoints[axis][i] = std::strtod(value.c_str(), nullptr);
            }
        }
        Grid grid(pantr::grid::TensorProductGrid<double>(breakpoints), factor);

        std::size_t n_ops = 0;
        std::cin >> token >> n_ops;
        for (std::size_t op = 0; op < n_ops; ++op) {
            std::string kind;
            std::cin >> token >> kind;
            if (kind == "refine" || kind == "coarsen") {
                std::int64_t level = 0;
                std::cin >> level;
                Ints lo(d);
                Ints hi(d);
                for (std::size_t k = 0; k < d; ++k) {
                    std::cin >> lo[k];
                }
                for (std::size_t k = 0; k < d; ++k) {
                    std::cin >> hi[k];
                }
                grid = kind == "refine" ? grid.refine(level, lo, hi)
                                        : grid.coarsen(level, lo, hi);
            } else {
                std::size_t count = 0;
                std::cin >> count;
                Ints ids(count);
                for (std::size_t i = 0; i < count; ++i) {
                    std::cin >> ids[i];
                }
                grid = kind == "refine_cells" ? grid.refine_cells(ids) : grid.coarsen_cells(ids);
            }
        }

        std::size_t n_requested = 0;
        std::cin >> token >> n_requested;
        Ints requested(n_requested);
        for (std::size_t i = 0; i < n_requested; ++i) {
            std::cin >> requested[i];
        }

        std::printf("RESULT %lld %lld\n", static_cast<long long>(grid.num_cells()),
                    static_cast<long long>(grid.max_level()));
        std::printf("REPR %s\n", grid.to_string().c_str());
        Ints midx(d);
        std::printf("CELLS");
        for (std::int64_t cid = 0; cid < grid.num_cells(); ++cid) {
            grid.cell_multi_index(cid, midx);
            std::printf(" %lld", static_cast<long long>(grid.cell_level(cid)));
            for (std::size_t k = 0; k < d; ++k) {
                std::printf(" %lld", static_cast<long long>(midx[k]));
            }
        }
        std::printf("\n");

        const CellExport<double> mesh = grid.export_cells();

        // The header's own claim, measured on this backend: the worst ratio of
        // |export corner - cell_bounds corner| to the bound derived for it. A bound of
        // zero admits only an exact match, so it is reported as 0 or as infinity.
        const auto corners = static_cast<std::size_t>(std::int64_t{1} << ndim);
        std::vector<double> cell_lo(d);
        std::vector<double> cell_hi(d);
        double margin = 0.0;
        for (std::int64_t cid = 0; cid < grid.num_cells(); ++cid) {
            grid.cell_bounds(cid, cell_lo, cell_hi);
            grid.cell_multi_index(cid, midx);
            const std::int64_t level = grid.cell_level(cid);
            for (std::size_t c = 0; c < corners; ++c) {
                for (std::size_t k = 0; k < d; ++k) {
                    std::int64_t span = 1;
                    for (std::int64_t l = 0; l < level; ++l) {
                        span *= factor[k];
                    }
                    const double base =
                        breakpoints[k][static_cast<std::size_t>(midx[k] / span)];
                    const double want = ((c >> k) & 1U) != 0U ? cell_hi[k] : cell_lo[k];
                    const auto vertex = static_cast<std::size_t>(
                        mesh.conn[static_cast<std::size_t>(cid) * corners + c]);
                    const double diff = std::fabs(mesh.points[vertex * d + k] - want);
                    const double bound = 2.0 * kGamma2 * std::fabs(want)
                                         + 2.0 * kGamma4 * std::fabs(want - base);
                    const double ratio =
                        bound > 0.0 ? diff / bound : (diff > 0.0 ? 1.0 / 0.0 : 0.0);
                    margin = ratio > margin ? ratio : margin;
                }
            }
        }
        std::printf("MARGIN %a\n", margin);

        std::printf("VERTICES %lld\nPOINTS", static_cast<long long>(mesh.num_vertices));
        for (const double value : mesh.points) {
            std::printf(" %a", value);
        }
        std::printf("\nCONN");
        for (const std::int64_t index : mesh.conn) {
            std::printf(" %lld", static_cast<long long>(index));
        }
        std::printf("\n");

        const GridRestriction<Grid> sub = grid.restrict(requested);
        std::printf("SUB %lld\nL2G", static_cast<long long>(sub.grid.num_cells()));
        for (const std::int64_t global : sub.local_to_global_cell) {
            std::printf(" %lld", static_cast<long long>(global));
        }
        std::printf("\nSUBSET");
        for (const std::uint8_t flag : sub.in_subset) {
            std::printf(" %d", static_cast<int>(flag));
        }
        std::printf("\nEND\n");
    }
    return 0;
}
"""


def _random_case(rng: np.random.Generator) -> tuple[HierarchicalGrid, list[str], list[int]]:
    """Draw a random hierarchy, a random operation sequence and a restriction request.

    Args:
        rng (np.random.Generator): The source of randomness.

    Returns:
        tuple[HierarchicalGrid, list[str], list[int]]: The final oracle grid, the
        operations that were actually applied, and the cell ids to restrict over.
    """
    ndim = int(rng.integers(1, 4))
    factor = [int(rng.choice([1, 2, 3])) for _ in range(ndim)]
    if all(f == 1 for f in factor):
        factor[int(rng.integers(0, ndim))] = 2
    breakpoints = []
    for _ in range(ndim):
        n = int(rng.integers(1, 4))
        interior = rng.uniform(-1.0, 1.0, n - 1)
        breakpoints.append(np.sort(np.concatenate([[-1.0, 1.0], interior])))
    grid = hierarchical_grid(TensorProductGrid(breakpoints), tuple(factor))

    applied: list[str] = []
    for _ in range(int(rng.integers(1, 6))):
        kind = str(rng.choice(["refine", "refine", "refine_cells", "coarsen", "coarsen_cells"]))
        try:
            if kind in ("refine", "coarsen"):
                level = int(rng.integers(0, grid.max_level + 1))
                extent = grid.level_cells_per_axis(level)
                lo = [int(rng.integers(0, extent[k])) for k in range(ndim)]
                hi = [int(rng.integers(lo[k] + 1, extent[k] + 1)) for k in range(ndim)]
                grid = (
                    grid.refine(level, lo, hi) if kind == "refine" else grid.coarsen(level, lo, hi)
                )
                applied.append(f"op {kind} {level} " + " ".join(str(v) for v in [*lo, *hi]))
            else:
                count = int(rng.integers(1, min(grid.num_cells, 8) + 1))
                ids = sorted({int(i) for i in rng.integers(0, grid.num_cells, count)})
                grid = grid.refine_cells(ids) if kind == "refine_cells" else grid.coarsen_cells(ids)
                applied.append(f"op {kind} {len(ids)} " + " ".join(str(i) for i in ids))
        except ValueError:
            continue  # an invalid box; the refusal paths are covered by the unit tests

    count = int(rng.integers(1, min(grid.num_cells, 5) + 1))
    requested = sorted({int(i) for i in rng.integers(0, grid.num_cells, count)})
    return grid, applied, requested


def _spec(grid_seed: tuple[HierarchicalGrid, list[str], list[int]], root: HierarchicalGrid) -> str:
    """Render one case as the driver's input block.

    Args:
        grid_seed (tuple): The `_random_case` triple.
        root (HierarchicalGrid): The unrefined grid the operations start from.

    Returns:
        str: The block.
    """
    _, applied, requested = grid_seed
    ndim = root.ndim
    lines = ["CASE", f"ndim {ndim}", "factor " + " ".join(str(f) for f in root.factor)]
    for k in range(ndim):
        bp = np.asarray(root.root.breakpoints[k], dtype=np.float64)
        lines.append(f"axis {k} {bp.size} " + " ".join(float(v).hex() for v in bp))
    lines.append(f"ops {len(applied)}")
    lines.extend(applied)
    lines.append(f"restrict {len(requested)} " + " ".join(str(i) for i in requested))
    return "\n".join(lines)


def _oracle_answers(grid: HierarchicalGrid, requested: list[int]) -> dict[str, object]:
    """Collect everything the driver prints, from the oracle.

    Args:
        grid (HierarchicalGrid): The final grid.
        requested (list[int]): The restriction request.

    Returns:
        dict[str, object]: The answers, keyed by the driver's section names.
    """
    points, conn = grid.export_cells()
    sub = grid.restrict(requested)
    margin = 0.0
    for cid in range(grid.num_cells):
        midx = grid.cell_multi_index(cid)
        level = grid.cell_level(cid)
        lo, hi = grid.cell_bounds(cid)
        for corner in range(1 << grid.ndim):
            for k in range(grid.ndim):
                base = float(grid.root.breakpoints[k][midx[k] // (grid.factor[k] ** level)])
                want = float(hi[k] if (corner >> k) & 1 else lo[k])
                diff = abs(float(points[conn[cid, corner], k]) - want)
                bound = _corner_bound(want, base)
                margin = max(margin, diff / bound if bound > 0.0 else float(diff > 0.0) * np.inf)
    cells: list[int] = []
    for cid in range(grid.num_cells):
        cells.append(grid.cell_level(cid))
        cells.extend(grid.cell_multi_index(cid))
    return {
        "num_cells": grid.num_cells,
        "max_level": grid.max_level,
        "repr": repr(grid),
        "cells": cells,
        "margin": margin,
        "vertices": points.shape[0],
        "points": points,
        "conn": conn.ravel().tolist(),
        "sub": sub.grid.num_cells,
        "l2g": sub.local_to_global_cell.tolist(),
        "subset": sub.in_subset.astype(np.int64).tolist(),
    }


def _corner_bound(x: float, root_lo: float) -> float:
    """Bound the two backends' disagreement at one exported coordinate.

    Args:
        x (float): The coordinate as the oracle computed it.
        root_lo (float): Lower breakpoint of the root cell holding it.

    Returns:
        float: The bound.
    """
    return 2.0 * _gamma(2.0) * abs(x) + 2.0 * _gamma(4.0) * abs(x - root_lo)


def _point_bounds(grid: HierarchicalGrid, points: np.ndarray) -> np.ndarray:
    """Per-coordinate bound for every exported vertex.

    Each vertex lies in some root cell; the widest root cell on an axis bounds every
    ``|x - b|`` on that axis, which is what makes this computable without inverting the
    deduplication.

    Args:
        grid (HierarchicalGrid): The grid the vertices came from.
        points (np.ndarray): ``(n, ndim)`` vertices.

    Returns:
        np.ndarray: ``(n, ndim)`` bounds.
    """
    bounds = np.empty_like(points)
    for k in range(grid.ndim):
        bp = np.asarray(grid.root.breakpoints[k], dtype=np.float64)
        widest = float(np.max(np.diff(bp)))
        bounds[:, k] = [
            2.0 * _gamma(2.0) * abs(float(x)) + 2.0 * _gamma(4.0) * widest for x in points[:, k]
        ]
    return bounds


def _parse(stream: list[str], index: int) -> tuple[dict[str, object], int]:
    """Read one driver result block.

    Args:
        stream (list[str]): The driver's output lines.
        index (int): Where the block starts.

    Returns:
        tuple[dict[str, object], int]: The block and the index just past it.
    """
    got: dict[str, object] = {}
    head = stream[index].split()
    got["num_cells"] = int(head[1])
    got["max_level"] = int(head[2])
    got["repr"] = stream[index + 1][len("REPR ") :]
    got["cells"] = [int(v) for v in stream[index + 2].split()[1:]]
    got["margin"] = float.fromhex(stream[index + 3].split()[1])
    got["vertices"] = int(stream[index + 4].split()[1])
    got["points"] = np.array(
        [float.fromhex(v) for v in stream[index + 5].split()[1:]], dtype=np.float64
    )
    got["conn"] = [int(v) for v in stream[index + 6].split()[1:]]
    got["sub"] = int(stream[index + 7].split()[1])
    got["l2g"] = [int(v) for v in stream[index + 8].split()[1:]]
    got["subset"] = [int(v) for v in stream[index + 9].split()[1:]]
    return got, index + 11


_EXACT_KEYS = (
    "num_cells",
    "max_level",
    "repr",
    "cells",
    "vertices",
    "conn",
    "sub",
    "l2g",
    "subset",
)
"""The answers compared for exact equality; every one is integers, counts or a repr."""


def _draw(
    cases: int, seed: int
) -> tuple[list[str], list[dict[str, object]], list[HierarchicalGrid]]:
    """Draw the cases and run the oracle over them.

    Args:
        cases (int): How many to draw.
        seed (int): The generator seed.

    Returns:
        tuple: The driver input blocks, the oracle's answers, and the final grids.
    """
    rng = np.random.default_rng(seed)
    specs: list[str] = []
    expected: list[dict[str, object]] = []
    grids: list[HierarchicalGrid] = []
    for _ in range(cases):
        case = _random_case(rng)
        grid, _, requested = case
        # `refine` and `coarsen` never touch the root, so the unrefined grid the
        # operations started from is recoverable from the final one.
        specs.append(_spec(case, hierarchical_grid(grid.root, grid.factor)))
        expected.append(_oracle_answers(grid, requested))
        grids.append(grid)
    return specs, expected, grids


def _run_driver(specs: list[str], args: argparse.Namespace) -> tuple[list[str], pathlib.Path]:
    """Build and run the C++ driver over the cases.

    Args:
        specs (list[str]): The input blocks.
        args (argparse.Namespace): The parsed command line.

    Returns:
        tuple[list[str], pathlib.Path]: The driver's output lines and its work directory.
    """
    includes = ["cpp/include", *args.include]
    for candidate in (args.build / "_deps/eigen-src", args.build / "_deps/mdspan-src/include"):
        if candidate.is_dir():
            includes.append(str(candidate))
    workdir = pathlib.Path(tempfile.mkdtemp(prefix="pantr-hier-parity-"))
    source = workdir / "driver.cpp"
    source.write_text(_DRIVER)
    program = workdir / "driver"
    command = [args.compiler, "-std=c++20", "-O2", "-o", str(program), str(source)]
    for path in includes:
        command += ["-I", path]
    print(" ".join(command))
    subprocess.run(command, check=True)
    result = subprocess.run(
        [str(program)], input="\n".join(specs), capture_output=True, text=True, check=True
    )
    return result.stdout.splitlines(), workdir


def _compare(
    lines: list[str], expected: list[dict[str, object]], grids: list[HierarchicalGrid]
) -> tuple[list[str], int, int, float, list[float]]:
    """Compare the driver's answers against the oracle's.

    Args:
        lines (list[str]): The driver's output.
        expected (list[dict[str, object]]): The oracle's answers.
        grids (list[HierarchicalGrid]): The final grids, for the coordinate bounds.

    Returns:
        tuple: The mismatches, the bitwise-identical coordinate count, the total
        coordinate count, the largest difference seen, and the worst
        ``|export - cell_bounds| / bound`` ratio on each backend, Python first.
    """
    mismatches: list[str] = []
    bitwise = 0
    coordinates = 0
    worst = 0.0
    margins = [0.0, 0.0]
    index = 0
    for case, want in enumerate(expected):
        got, index = _parse(lines, index)
        mismatches += [
            f"case {case}: {key} differs" for key in _EXACT_KEYS if got[key] != want[key]
        ]
        margins[0] = max(margins[0], float(str(want["margin"])))
        margins[1] = max(margins[1], float(str(got["margin"])))
        if margins[0] > 1.0 or margins[1] > 1.0:
            mismatches.append(f"case {case}: a corner exceeds the derived bound")
        want_points = np.asarray(want["points"], dtype=np.float64)
        got_points = np.asarray(got["points"], dtype=np.float64).reshape(want_points.shape)
        difference = np.abs(got_points - want_points)
        coordinates += want_points.size
        bitwise += int(np.count_nonzero(difference == 0.0))
        if want_points.size:
            worst = max(worst, float(np.max(difference)))
        if np.any(difference > _point_bounds(grids[case], want_points)):
            mismatches.append(f"case {case}: a vertex coordinate exceeds its bound")
    return mismatches, bitwise, coordinates, worst, margins


def main() -> int:
    """Run the comparison.

    Returns:
        int: ``0`` when every case agrees.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    # 400 is a smoke size, not the size that finds a rare ordering bug. The
    # `coarsen_cells` parent-order defect this script was extended to catch first
    # appeared at case 3553 of a 4000-case sweep and is invisible at this default.
    parser.add_argument("--cases", type=int, default=400)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--build", type=pathlib.Path, default=pathlib.Path("build/gcc"))
    parser.add_argument("--include", action="append", default=[])
    parser.add_argument("--compiler", default="g++")
    parser.add_argument("--keep", action="store_true", help="keep the generated program")
    args = parser.parse_args()

    specs, expected, grids = _draw(args.cases, args.seed)
    lines, workdir = _run_driver(specs, args)
    mismatches, bitwise, coordinates, worst, margins = _compare(lines, expected, grids)

    print(f"cases                 {len(expected)}")
    cells = sum(int(str(w["num_cells"])) for w in expected)
    vertices = sum(int(str(w["vertices"])) for w in expected)
    print(f"cells compared        {cells}")
    print(f"vertices compared     {vertices}")
    print(f"coordinates compared  {coordinates}")
    print(f"bitwise identical     {bitwise} of {coordinates}")
    print(f"largest difference    {worst:.3e}")
    print(f"bound margin, python  {margins[0]:.3f} of 1")
    print(f"bound margin, c++     {margins[1]:.3f} of 1")
    print(f"mismatches            {len(mismatches)}")
    for line in mismatches[:20]:
        print("  " + line)

    if args.keep:
        print(f"kept                  {workdir}")
    else:
        shutil.rmtree(workdir)
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
